// GENERATED by scripts/gen-cheats.py -- do not edit.
//
// Codes from DeadSkullzJr's NDS(i) Cheat Database, validated against the
// opcodes PSZPlugin implements. Anything using an unsupported opcode is refused
// at generation time rather than emitted and mis-executed.

#ifndef PSZCHEATS_H
#define PSZCHEATS_H

namespace PSZMix
{

static const unsigned int kCheat_MAX_HP[] = {
    0x121A21FEu, 0x0000270Fu,
    0x121A210Cu, 0x0000270Fu,
};

static const unsigned int kCheat_MAX_PP[] = {
    0x121A2200u, 0x000003E7u,
    0x121A210Eu, 0x000003E7u,
};

static const unsigned int kCheat_MAX_ATP[] = {
    0x121A2110u, 0x0000270Fu,
};

static const unsigned int kCheat_MAX_DFP[] = {
    0x121A2112u, 0x0000270Fu,
};

static const unsigned int kCheat_EXP_X2[] = {
    0x02000000u, 0x1C0D1C06u,
    0x02000004u, 0xF03E006Du,
    0x12000008u, 0x0000F912u,
    0x92000008u, 0x0000F912u,
    0x1203E22Au, 0x0000F7C1u,
    0x1203E22Cu, 0x0000FEE9u,
    0xD2000000u, 0x00000000u,
};

static const unsigned int kCheat_EXP_X4[] = {
    0x02000000u, 0x1C0D1C06u,
    0x02000004u, 0xF03E00ADu,
    0x12000008u, 0x0000F912u,
    0x92000008u, 0x0000F912u,
    0x1203E22Au, 0x0000F7C1u,
    0x1203E22Cu, 0x0000FEE9u,
    0xD2000000u, 0x00000000u,
};

static const unsigned int kCheat_EXP_X8[] = {
    0x02000000u, 0x1C0D1C06u,
    0x02000004u, 0xF03E00EDu,
    0x12000008u, 0x0000F912u,
    0x92000008u, 0x0000F912u,
    0x1203E22Au, 0x0000F7C1u,
    0x1203E22Cu, 0x0000FEE9u,
    0xD2000000u, 0x00000000u,
};

static const unsigned int kCheat_MATERIALS_X99[] = {
    0x02242744u, 0x18C00000u,
    0x02242740u, 0x00000503u,
    0x02242754u, 0x18C00000u,
    0x02242750u, 0x00010503u,
    0x02242764u, 0x18C00000u,
    0x02242760u, 0x00020503u,
    0x02242774u, 0x18C00000u,
    0x02242770u, 0x00030503u,
    0x02242784u, 0x18C00000u,
    0x02242780u, 0x00040503u,
    0x02242794u, 0x18C00000u,
    0x02242790u, 0x00050503u,
    0x022427A4u, 0x18C00000u,
    0x022427A0u, 0x00060503u,
};

static const unsigned int kCheat_SOUL_ITEMS_X99[] = {
    0x022426B4u, 0x18C00000u,
    0x022426B0u, 0x00280303u,
    0x022426C4u, 0x18C00000u,
    0x022426C0u, 0x00290303u,
    0x022426D4u, 0x18C00000u,
    0x022426D0u, 0x002A0303u,
    0x022426E4u, 0x18C00000u,
    0x022426E0u, 0x002B0303u,
    0x022426F4u, 0x18C00000u,
    0x022426F0u, 0x002C0303u,
    0x02242704u, 0x18C00000u,
    0x02242700u, 0x002C0303u,
    0x02242714u, 0x18C00000u,
    0x02242710u, 0x002D0303u,
    0x02242724u, 0x18C00000u,
    0x02242720u, 0x002E0303u,
    0x02242734u, 0x18C00000u,
    0x02242730u, 0x002F0303u,
};

struct GeneratedCheat { const char* name; const char* env; bool defaultOn;
                        const unsigned int* codes; int words; };

static const GeneratedCheat kGeneratedCheats[] = {
    { "Max Health", "PSZ_CHEAT_MAX_HP", false, kCheat_MAX_HP, 4 },   // OptIn
    { "Max PP", "PSZ_CHEAT_MAX_PP", false, kCheat_MAX_PP, 4 },   // OptIn
    { "Max Attack", "PSZ_CHEAT_MAX_ATP", false, kCheat_MAX_ATP, 2 },   // OptIn
    { "Max Defense", "PSZ_CHEAT_MAX_DFP", false, kCheat_MAX_DFP, 2 },   // OptIn
    { "x2", "PSZ_CHEAT_EXP_X2", false, kCheat_EXP_X2, 14 },   // OptIn
    { "x4", "PSZ_CHEAT_EXP_X4", false, kCheat_EXP_X4, 14 },   // OptIn
    { "x8", "PSZ_CHEAT_EXP_X8", false, kCheat_EXP_X8, 14 },   // OptIn
    { "Boost Material x99 each", "PSZ_CHEAT_MATERIALS_X99", false, kCheat_MATERIALS_X99, 28 },   // OptIn
    { "Soul Item x99 each", "PSZ_CHEAT_SOUL_ITEMS_X99", false, kCheat_SOUL_ITEMS_X99, 36 },   // OptIn
};
static const int kNumGeneratedCheats =
    sizeof(kGeneratedCheats) / sizeof(kGeneratedCheats[0]);

}

#endif // PSZCHEATS_H
