// GENERATED by scripts/gen-overlay-fingerprints.py -- do not edit.
//
// CRC32 of the first 512 bytes of each ARM9 overlay that loads at 0x0211E640.
// They all share that one slot, so exactly one is resident at a time and which
// one it is IS the game's own notion of what it is doing (psz-re
// docs/game-state.md). These are hashes, not game data.

#ifndef PSZOVERLAYIDS_H
#define PSZOVERLAYIDS_H

namespace PSZMix
{

struct OverlayFingerprint { int id; unsigned int crc; };

static const OverlayFingerprint kOverlayFingerprints[] = {
    {  0, 0x55AB8560u },
    {  1, 0xDFE06F7Eu },
    {  2, 0xCFA4BF8Fu },
    {  3, 0x9A1F02C3u },
    {  4, 0x0116CF67u },
    {  5, 0xCFE8B994u },
    {  6, 0xD2CF3205u },
    {  7, 0x71D6A941u },
    {  8, 0xBE9F7DDBu },
    {  9, 0xA46D2C27u },
    { 10, 0xF6D4CB33u },
    { 11, 0x54B6064Bu },
    { 12, 0xCE357ADFu },
    { 13, 0x8A9AB09Bu },
    { 14, 0x3A6C591Cu },
    { 15, 0x2E009B6Bu },
    { 16, 0xB72E5A70u },
    { 17, 0xBF39D7E2u },
    { 18, 0x0B0D1285u },
};
static const int kNumOverlayFingerprints =
    sizeof(kOverlayFingerprints) / sizeof(kOverlayFingerprints[0]);

}

#endif // PSZOVERLAYIDS_H
