#!/usr/bin/env python3
"""Emit psz/PSZOverlayIDs.h -- a CRC32 per slot overlay.

The resident ARM9 overlay at 0x0211E640 IS the game's mode (psz-re,
docs/game-state.md). Recovering which one is resident at runtime needs a way to
recognise it without shipping the ROM's overlay images, so this stores a 32-bit
hash of each overlay's first 512 bytes. Hashes, not content: 19 numbers.

Regenerate:  python3 scripts/gen-overlay-fingerprints.py <psz-re-build-dir>
"""
import sys, json, zlib, pathlib

build = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                     else "/home/kion/projects/psz-re/build")
meta = json.loads((build / "rom_meta.json").read_text())
SLOT = 0x0211E640

rows = []
for o in meta["overlays"]["arm9"]:
    if o["ram_addr"] != SLOT:
        continue
    img = (build / "overlay_arm9_dec" / f"overlay_{o['id']:04d}.bin").read_bytes()
    rows.append((o["id"], zlib.crc32(img[:512]) & 0xFFFFFFFF))

out = pathlib.Path(__file__).resolve().parent.parent / "psz" / "PSZOverlayIDs.h"
with out.open("w") as f:
    f.write("""// GENERATED by scripts/gen-overlay-fingerprints.py -- do not edit.
//
// CRC32 of the first 512 bytes of each ARM9 overlay that loads at 0x0211E640.
// They all share that one slot, so exactly one is resident at a time and which
// one it is IS the game's own notion of what it is doing (psz-re
// docs/game-state.md). These are hashes, not game data.

#ifndef PSZOVERLAYIDS_H
#define PSZOVERLAYIDS_H

namespace PSZMix
{

struct OverlayFingerprint { int id; unsigned int crc; };

static const OverlayFingerprint kOverlayFingerprints[] = {
""")
    for i, c in rows:
        f.write("    { %2d, 0x%08Xu },\n" % (i, c))
    f.write("""};
static const int kNumOverlayFingerprints =
    sizeof(kOverlayFingerprints) / sizeof(kOverlayFingerprints[0]);

}

#endif // PSZOVERLAYIDS_H
""")
print(f"wrote {out} with {len(rows)} fingerprints")
