#!/usr/bin/env python3
"""Emit psz/PSZCheats.h from cheats/psz_C24E_melonds.xml.

Two classes, and the distinction is the point:

  QOL    quality-of-life and presentation. ON by default, because they are what
         makes this build pleasant rather than what makes the game easier.
  OPTIN  grind-skipping. OFF by default. These change the game, so nobody gets
         them without asking.

Codes are VALIDATED against the opcodes PSZPlugin's interpreter actually
implements, and a cheat using anything else is refused rather than emitted. A
misread AR code writes to an arbitrary address, and a cheat that quietly corrupts
emulated RAM is far worse than one that is missing.
"""
import re, sys, pathlib

SUPPORTED = {0x0, 0x1, 0x2, 0x9, 0xD}   # write u32/u16/u8, u16 conditional, end

# name in the XML -> (identifier, class). Curated deliberately: a short list
# people will actually enable beats every code in the database.
WANTED = [
    ("Max Health",              "MAX_HP",        "OptIn"),
    ("Max PP",                  "MAX_PP",        "OptIn"),
    ("Max Attack",              "MAX_ATP",       "OptIn"),
    ("Max Defense",             "MAX_DFP",       "OptIn"),
    ("x2",                      "EXP_X2",        "OptIn"),
    ("x4",                      "EXP_X4",        "OptIn"),
    ("x8",                      "EXP_X8",        "OptIn"),
    ("Boost Material x99 each", "MATERIALS_X99", "OptIn"),
    ("Soul Item x99 each",      "SOUL_ITEMS_X99","OptIn"),
    ("Force Rare Room (stage nr)", "FORCE_RARE_ROOM", "OptIn"),
    ("Force Coliseum (nr2)",       "FORCE_COLISEUM",  "OptIn"),
]

root = pathlib.Path(__file__).resolve().parent.parent
xml = (root / "cheats" / "psz_C24E_melonds.xml").read_text()
blocks = dict((n, c) for n, c in
              re.findall(r"<cheat>\s*<name>([^<]+)</name>.*?<codes>(.*?)</codes>", xml, re.S))

emitted, refused = [], []
for name, ident, cls in WANTED:
    if name not in blocks:
        refused.append((name, "not in the database")); continue
    words = blocks[name].split()
    if len(words) % 2:
        refused.append((name, "odd word count")); continue
    bad = sorted({int(w[0], 16) for w in words[::2]} - SUPPORTED)
    if bad:
        refused.append((name, "opcode(s) " + ", ".join("0x%X" % b for b in bad)))
        continue
    emitted.append((name, ident, cls, [int(w, 16) for w in words]))

out = root / "psz" / "PSZCheats.h"
with out.open("w") as f:
    f.write("""// GENERATED by scripts/gen-cheats.py -- do not edit.
//
// Codes from DeadSkullzJr's NDS(i) Cheat Database, validated against the
// opcodes PSZPlugin implements. Anything using an unsupported opcode is refused
// at generation time rather than emitted and mis-executed.

#ifndef PSZCHEATS_H
#define PSZCHEATS_H

namespace PSZMix
{

""")
    for _, ident, _, words in emitted:
        f.write("static const unsigned int kCheat_%s[] = {\n" % ident)
        for i in range(0, len(words), 2):
            f.write("    0x%08Xu, 0x%08Xu,\n" % (words[i], words[i + 1]))
        f.write("};\n\n")
    f.write("struct GeneratedCheat { const char* name; const char* env; bool defaultOn;\n"
            "                        const unsigned int* codes; int words; };\n\n"
            "static const GeneratedCheat kGeneratedCheats[] = {\n")
    for name, ident, cls, words in emitted:
        f.write('    { "%s", "PSZ_CHEAT_%s", false, kCheat_%s, %d },   // %s\n'
                % (name.replace('"', ''), ident, ident, len(words), cls))
    f.write("};\nstatic const int kNumGeneratedCheats =\n"
            "    sizeof(kGeneratedCheats) / sizeof(kGeneratedCheats[0]);\n\n}\n\n"
            "#endif // PSZCHEATS_H\n")

print(f"emitted {len(emitted)} cheats -> {out}")
for n, why in refused:
    print(f"  REFUSED {n}: {why}")
